#!/bin/bash

echo "🚀 SMITE Plugins Installer"
echo "=========================="
echo ""
echo "Installing all SMITE agents from marketplace..."
echo ""
echo "⚠️  Please copy and paste these commands one by one in Claude Code:"
echo ""
echo "/plugin marketplace add Pamacea/smite-marketplace"
echo ""
echo "# Install all agents in workflow order:"
echo "/plugin install smite-initializer@smite-marketplace"
echo "/plugin install smite-analyst@smite-marketplace"
echo "/plugin install smite-architect@smite-marketplace"
echo "/plugin install smite-economist@smite-marketplace"
echo "/plugin install smite-aura@smite-marketplace"
echo "/plugin install smite-constructor@smite-marketplace"
echo "/plugin install smite-gatekeeper@smite-marketplace"
echo "/plugin install smite-handover@smite-marketplace"
echo "/plugin install smite-surgeon@smite-marketplace"
echo "/plugin install smite-orchestrator@smite-marketplace"
echo ""
echo "✅ Installation complete!"
echo ""
echo "Start using SMITE with:"
echo "  /smite:init"
