#!/bin/bash

echo "🗑️  SMITE Plugins Uninstaller"
echo "=============================="
echo ""
echo "This will uninstall all SMITE agents from your Claude Code."
echo ""
echo "Plugins to uninstall:"
echo "  - smite-initializer"
echo "  - smite-analyst"
echo "  - smite-architect"
echo "  - smite-economist"
echo "  - smite-aura"
echo "  - smite-constructor"
echo "  - smite-gatekeeper"
echo "  - smite-handover"
echo "  - smite-surgeon"
echo "  - smite-orchestrator"
echo ""
echo "⚠️  Please copy and paste these commands one by one in Claude Code:"
echo ""
echo "/plugin uninstall smite-initializer"
echo "/plugin uninstall smite-analyst"
echo "/plugin uninstall smite-architect"
echo "/plugin uninstall smite-economist"
echo "/plugin uninstall smite-aura"
echo "/plugin uninstall smite-constructor"
echo "/plugin uninstall smite-gatekeeper"
echo "/plugin uninstall smite-handover"
echo "/plugin uninstall smite-surgeon"
echo "/plugin uninstall smite-orchestrator"
echo ""
echo "✅ After uninstalling, you can reinstall with:"
echo ""
echo "/plugin marketplace add Pamacea/smite-marketplace"
echo ""
echo "Then install individual agents or use the full install script."
