#!/usr/bin/env node

/**
 * SMITE Orchestrator - Agent Completion Handler
 *
 * Detects agent completion and generates next agent suggestion.
 * Hook: SubagentStop
 *
 * Usage:
 *   ts-node agent-complete.ts <agent_name> [project_dir]
 */

import * as fs from 'fs';
import * as path from 'path';
import { loadState, saveState, init, AgentName } from './state-manager';
import { generateSuggestion } from './suggest-next';

interface CompleteResult {
  success: boolean;
  message?: string;
  next_agent?: AgentName | null;
  suggestion_file?: string;
  error?: string;
}

/**
 * Handle agent completion
 */
function handleAgentComplete(
  agentName: string,
  projectDir: string = process.cwd()
): CompleteResult {
  try {
    // Load current state
    let state = loadState(projectDir);

    if (!state) {
      state = init(projectDir);
    }

    // Update state
    state.current_agent = null; // Clear current agent (completed)
    state.last_completed_agent = agentName as AgentName;

    // Track agent call if not already tracked
    if (!state.agents_called.includes(agentName as AgentName)) {
      state.agents_called.push(agentName as AgentName);
    }

    saveState(state, projectDir);

    // Get next agent suggestion
    const suggestion = generateSuggestion(projectDir);

    // Create suggestion file
    createSuggestionFile(agentName, suggestion, projectDir);

    return {
      success: true,
      message: `Agent ${agentName} completed`,
      next_agent: suggestion.next,
      suggestion_file: '.smite/suggestions/next-action.md'
    };

  } catch (error: any) {
    return {
      success: false,
      error: error.message
    };
  }
}

/**
 * Create suggestion file
 */
function createSuggestionFile(
  completedAgent: string,
  suggestion: SuggestionResult,
  projectDir: string
): void {
  const suggestionPath = path.join(projectDir, '.smite', 'suggestions', 'next-action.md');

  const content = `# 🎯 NEXT AGENT SUGGESTION

**Generated**: ${new Date().toISOString()}
**Completed**: ${completedAgent}

---

## ✅ Completed: ${completedAgent.toUpperCase()}

Agent has finished its work.

---

## 🎯 Recommendation

${suggestion.next ? `**Next Agent**: \`/smite:${suggestion.next}\`` : '**Workflow Complete!**'}

${suggestion.reason ? `\n**Reason**: ${suggestion.reason}` : ''}

---

## 📊 Workflow Progress

\`\`\`
${suggestion.workflow_progress}
\`\`\`

---

## 🚀 Quick Start

${suggestion.next ? `To continue the workflow, run:\n\n\`\`\`\n/smite:${suggestion.next}\n\`\`\`` : '🎉 All agents completed! Review the artifacts in the `docs/` directory.'}

---

## 📋 Deliverables

${suggestion.deliverables || '*No deliverables yet*'}

---

*Suggestions are automatically generated by SMITE Orchestrator*
`;

  fs.writeFileSync(suggestionPath, content, 'utf-8');
}

interface SuggestionResult {
  next: AgentName | null;
  reason?: string;
  workflow_progress: string;
  deliverables?: string;
}

/**
 * CLI interface
 */
function main(): void {
  const args = process.argv.slice(2);

  if (args.length < 1) {
    console.error('Usage: ts-node agent-complete.ts <agent_name> [project_dir]');
    process.exit(1);
  }

  const agentName = args[0];
  const projectDir = args[1] || process.cwd();

  const result = handleAgentComplete(agentName, projectDir);

  if (result.success) {
    console.log(JSON.stringify(result, null, 2));
  } else {
    console.error(JSON.stringify(result));
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  main();
}

export {
  handleAgentComplete
};
