#!/usr/bin/env node

/**
 * SMITE Orchestrator - Handoff Artifact Generator
 *
 * Auto-generates MISSION_BRIEF templates for smooth agent handoffs.
 * Creates context from previous agent for next agent.
 *
 * Usage:
 *   ts-node generate-handoff.ts <next_agent> [project_dir]
 */

import * as fs from 'fs';
import * as path from 'path';
import { loadState, AgentName } from './state-manager';
import { AGENT_INFO } from './suggest-next';

interface HandoffResult {
  success: boolean;
  handoff_file?: string;
  next_agent?: AgentName;
  error?: string;
}

/**
 * Generate handoff document
 */
function generateHandoff(
  nextAgent: AgentName,
  projectDir: string = process.cwd()
): HandoffResult {
  try {
    const state = loadState(projectDir);

    if (!state) {
      return {
        success: false,
        error: 'No active session found'
      };
    }

    // Create handoff content
    const content = generateHandoffContent(nextAgent, state, projectDir);

    // Write handoff file
    const handoffDir = path.join(projectDir, 'docs');
    if (!fs.existsSync(handoffDir)) {
      fs.mkdirSync(handoffDir, { recursive: true });
    }

    const handoffFile = path.join(handoffDir, `MISSION_BRIEF_${nextAgent.toUpperCase()}.md`);
    fs.writeFileSync(handoffFile, content, 'utf-8');

    return {
      success: true,
      handoff_file: handoffFile,
      next_agent: nextAgent
    };

  } catch (error: any) {
    return {
      success: false,
      error: error.message
    };
  }
}

/**
 * Generate handoff document content
 */
function generateHandoffContent(
  nextAgent: AgentName,
  state: any,
  projectDir: string
): string {
  const previousAgent = state.last_completed_agent || state.agents_called[state.agents_called.length - 1];
  const agentInfo = AGENT_INFO[nextAgent];

  let content = `# MISSION_BRIEF: ${nextAgent.toUpperCase()}

**Generated**: ${new Date().toISOString()}
**Session**: ${state.session_id}
**Previous Agent**: ${previousAgent ? previousAgent.toUpperCase() : 'None'}
**Current Phase**: ${state.phase}

---

## 🎯 MISSION OBJECTIVE

${agentInfo.description}

---

## 📋 CONTEXT FROM PREVIOUS AGENTS

`;

  // Add artifacts from previous agents
  if (state.artifacts.length > 0) {
    content += `### Artifacts Delivered\n\n`;

    // Group artifacts by agent
    const byAgent: Record<string, any[]> = {};
    state.artifacts.forEach((artifact: any) => {
      const agent = artifact.agent || 'unknown';
      if (!byAgent[agent]) {
        byAgent[agent] = [];
      }
      byAgent[agent].push(artifact);
    });

    // List artifacts by agent
    Object.entries(byAgent).forEach(([agent, artifacts]) => {
      content += `#### ${agent.toUpperCase()}\n\n`;
      artifacts.forEach((artifact: any) => {
        content += `- 📄 \`${artifact.path}\`\n`;
      });
      content += '\n';
    });
  } else {
    content += '*No artifacts from previous agents*\n\n';
  }

  content += `---

## 🎯 YOUR DELIVERABLES

${agentInfo.deliverables}

---

## 📊 WORKFLOW STATUS

**Agents Called**: ${state.agents_called.join(', ') || 'None'}
**Current Agent**: ${state.current_agent || 'None'}
**Phase**: ${state.phase}
**Artifacts Tracked**: ${state.artifacts.length}

---

## ✅ CHECKLIST

Use this checklist to ensure completion:

`;

  // Generate agent-specific checklist
  const checklist = generateChecklist(nextAgent);
  checklist.forEach(item => {
    content += `- [ ] ${item}\n`;
  });

  content += `

---

## 🔗 RESOURCES

### Relevant Documentation

`;

  // Add links to existing documentation
  const docsDir = path.join(projectDir, 'docs');
  if (fs.existsSync(docsDir)) {
    const files = fs.readdirSync(docsDir).filter((f: string) => f.endsWith('.md'));
    files.forEach((file: string) => {
      if (file !== `MISSION_BRIEF_${nextAgent.toUpperCase()}.md`) {
        content += `- [${file}](docs/${file})\n`;
      }
    });
  } else {
    content += '*No documentation yet*\n';
  }

  content += `

---

## 🚀 NEXT STEPS

After completing your mission:

1. Review your deliverables against the checklist
2. Ensure all documentation is up to date
3. Run quality checks if applicable
4. Mark mission as complete

---

**Generated by SMITE Orchestrator - Handoff System**
*Session ID: ${state.session_id}*
`;

  return content;
}

/**
 * Generate agent-specific checklist
 */
function generateChecklist(agent: AgentName): string[] {
  const checklists: Record<AgentName, string[]> = {
    initializer: [
      'Define technical stack',
      'Create project structure',
      'Set up build tools',
      'Initialize documentation',
      'Create configuration files'
    ],
    explorer: [
      'Map codebase architecture',
      'Identify dependencies',
      'Find components and functions',
      'Analyze patterns',
      'Document code structure'
    ],
    strategist: [
      'Analyze market landscape',
      'Identify competitors',
      'Define user personas',
      'Create business model',
      'Define pricing strategy',
      'Project financial scenarios'
    ],
    architect: [
      'Design system architecture',
      'Define database schema',
      'Specify API endpoints',
      'Create architecture diagrams',
      'Document technical decisions'
    ],
    aura: [
      'Define design tokens',
      'Create component library',
      'Establish style guide',
      'Build responsive layouts',
      'Document design patterns'
    ],
    constructor: [
      'Implement core features',
      'Write unit tests',
      'Follow architecture specs',
      'Maintain code quality',
      'Update documentation'
    ],
    gatekeeper: [
      'Review code quality',
      'Check type safety',
      'Validate test coverage',
      'Enforce standards',
      'Generate quality report'
    ],
    handover: [
      'Create API documentation',
      'Write README',
      'Create onboarding guide',
      'Document setup process',
      'Prepare knowledge transfer'
    ],
    surgeon: [
      'Analyze technical debt',
      'Refactor identified issues',
      'Optimize performance',
      'Improve type safety',
      'Document changes'
    ]
  };

  return checklists[agent] || ['Complete assigned tasks', 'Document work done', 'Test deliverables'];
}

/**
 * CLI interface
 */
function main(): void {
  const args = process.argv.slice(2);

  if (args.length < 1) {
    console.error('Usage: ts-node generate-handoff.ts <next_agent> [project_dir]');
    process.exit(1);
  }

  const nextAgent = args[0] as AgentName;
  const projectDir = args[1] || process.cwd();

  const result = generateHandoff(nextAgent, projectDir);

  if (result.success) {
    console.log(JSON.stringify(result, null, 2));
  } else {
    console.error(JSON.stringify(result));
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  main();
}

export {
  generateHandoff,
  generateChecklist
};
