#!/usr/bin/env node

/**
 * SMITE Orchestrator - Session Initialization
 *
 * Initializes a new SMITE workflow session with directory structure
 * and suggestion display mechanism.
 *
 * Usage:
 *   ts-node session-init.ts [project_dir]
 */

import * as fs from 'fs';
import * as path from 'path';

// Configuration
const STATE_DIR = '.smite';
const WORKFLOW_DIR = path.join(STATE_DIR, 'workflow');
const SUGGESTIONS_DIR = path.join(STATE_DIR, 'suggestions');

/**
 * Ensure all required directories exist
 */
function ensureDirectories(projectDir: string): void {
  const dirs = [
    path.join(projectDir, STATE_DIR),
    path.join(projectDir, WORKFLOW_DIR),
    path.join(projectDir, SUGGESTIONS_DIR),
    path.join(projectDir, 'docs') // For mission briefs and artifacts
  ];

  dirs.forEach(dir => {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
  });
}

/**
 * Create initial session info
 */
function createSessionInfo(projectDir: string): void {
  const sessionInfoPath = path.join(projectDir, WORKFLOW_DIR, 'session-info.md');

  const content = `# SMITE Workflow Session

**Started**: ${new Date().toISOString()}
**Project**: ${path.basename(projectDir)}
**Status**: Initialized

## Workflow Progress

\`\`\`
initializer → explorer → strategist → architect → aura → constructor → gatekeeper → handover
     [ ]           [ ]          [ ]         [ ]        [ ]       [ ]           [ ]         [ ]
\`\`\`

## Artifacts

*Session initialized. Artifacts will be tracked here.*

---

*This file is automatically maintained by SMITE Orchestrator*
`;

  fs.writeFileSync(sessionInfoPath, content, 'utf-8');
}

/**
 * Create suggestion display template
 */
function createSuggestionTemplate(projectDir: string): void {
  const templatePath = path.join(projectDir, SUGGESTIONS_DIR, 'next-action.md');

  const content = `# 🎯 NEXT ACTION SUGGESTION

**Generated**: ${new Date().toISOString()}

## Recommendation

Waiting for agent execution...

---

## Context

No agent has been executed yet. Start the workflow with:

\`\`\`
/smite:init
\`\`\`

---

*Suggestions are automatically generated by SMITE Orchestrator*
`;

  fs.writeFileSync(templatePath, content, 'utf-8');
}

/**
 * Initialize session
 */
function initSession(projectDir: string = process.cwd()): void {
  try {
    // Ensure directories exist
    ensureDirectories(projectDir);

    // Create session info
    createSessionInfo(projectDir);

    // Create suggestion template
    createSuggestionTemplate(projectDir);

    console.log(JSON.stringify({
      success: true,
      message: 'SMITE session initialized successfully',
      project_dir: projectDir,
      directories: {
        state: STATE_DIR,
        workflow: WORKFLOW_DIR,
        suggestions: SUGGESTIONS_DIR,
        docs: 'docs'
      }
    }));

  } catch (error: any) {
    console.error(JSON.stringify({
      success: false,
      error: error.message
    }));
    process.exit(1);
  }
}

/**
 * CLI interface
 */
function main(): void {
  const args = process.argv.slice(2);
  const projectDir = args[0] || process.cwd();

  initSession(projectDir);
}

// Run if called directly
if (require.main === module) {
  main();
}

export {
  initSession
};
