#!/usr/bin/env node
"use strict";
/**
 * Ralph Hook Installation Script
 *
 * Copies the stop-hook.js to the user's global .claude directory
 * and creates a wrapper that can locate the plugin regardless of installation path.
 */

const fs = require('fs');
const path = require('path');

// Paths
const pluginDir = __dirname;
const sourceHook = path.join(pluginDir, 'dist', 'stop-hook.js');
const globalClaudeDir = path.join(process.env.USERPROFILE || process.env.HOME, '.claude');
const globalPluginsDir = path.join(globalClaudeDir, 'plugins');
const installedHookPath = path.join(globalPluginsDir, 'ralph-stop-hook.js');

// Ensure directories exist
if (!fs.existsSync(globalPluginsDir)) {
  fs.mkdirSync(globalPluginsDir, { recursive: true });
}

// Create wrapper script that knows where the plugin is
const wrapperScript = `#!/usr/bin/env node
"use strict";
/**
 * Ralph Stop Hook Wrapper
 *
 * This wrapper is installed to the global .claude directory
 * and delegates to the actual plugin hook.
 *
 * Auto-generated by: ${path.basename(__filename)}
 * Plugin location: ${pluginDir}
 */

const path = require('path');
const { spawnSync } = require('child_process');

// Plugin installation path
const PLUGIN_DIR = ${JSON.stringify(pluginDir)};
const HOOK_PATH = path.join(PLUGIN_DIR, 'dist', 'stop-hook.js');

// Execute the actual hook
const result = spawnSync('node', [HOOK_PATH, ...process.argv.slice(2)], {
  cwd: process.cwd(),
  env: process.env,
  stdio: 'inherit'
});

// Exit with same code
process.exit(result.status || 0);
`;

// Write wrapper script
fs.writeFileSync(installedHookPath, wrapperScript, 'utf-8');

console.log('✅ Ralph stop hook installed successfully!');
console.log(`   Source: ${sourceHook}`);
console.log(`   Installed: ${installedHookPath}`);
